kind: ConfigMap
apiVersion: v1
metadata:
  name: simple-demo-webapp-config
  namespace: acme-customers
immutable: false
data:
  config.json: |-
    {
      "jumbotron": {
        "backgroundImage": "/ressources/header.png",
        "title": "ACME a fictive company at your service",
        "detail": "Customers Management"
      },
      "menu": {
        "title": "<script>document.documentElement.setAttribute('data-bs-theme', 'light');</script>",
        "items": [
          { "label": "Active Customers", "options": [ "active" ] },
          { "label": "Archive", "options": [ ]}
        ]
      },
      "table": {
        "header": [
          "Company Name",
          "Plan Type",
          "Contact",
          "Status"
        ],
        "data": [
          [ "Mirobec", "B-1",  "Mireille Lachance", "<div class='text-center blink text-warning'>NEED ACTION</div>"],
          [ "Axtal",  "C-C",      "Bob Tremblay", "<div class='text-center text-success'>ACTIVE</div>"],
          [ "Combo inc.", "B-1",      "Richard M.", "<div class='text-center text-success'>ACTIVE</div>"],
          [ "Zikaty eng.", "A+",   "Ti-Guy", "<div class='text-center text-success'>ACTIVE</div>"],
          [ "Michel Robert", "C-C",      "Maurice Robert", "<div class='text-center blink text-warning'>NEED ACTION</div>"],
          [ "WildHammer co.", "B-2",      "Fanny Tremblay", "<div class='text-center text-danger fw-bold'>EXPIRED</div>"]
        ]
      }
    }
  custom.css: |-

    body {
      background: white;
      color: #333;
    }

    table {
      background: white;
      color: #333;
    }

    .jumbotron {
      color: white;
    }

    .blink {
      animation: blinker 2s linear infinite;
    }

    @keyframes blinker {
      50% {
        opacity: 0;
      }
    }

    .table-body {
      /*font-family: "Courier New";*/
      font-family: monospace;
    }

    td:nth-child(3),
    th:nth-child(3) {
      text-align: left;
    }
    td:nth-child(4),
    th:nth-child(4) {
      text-align: center;
    }
    td:nth-child(5),
    th:nth-child(5) {
      text-align: center;
    }
    td:nth-child(6),
    th:nth-child(6) {
      text-align: center;
    }
