apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: acme-shared-pvc
spec:
  accessModes:
    - ReadWriteMany # Use RWX if multiple pods need to write at once
  resources:
    requests:
      storage: 50Mi