apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: acme-customers-dashboard

resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/config.yaml

configMapGenerator:
  - name: ressources-1
    namespace: acme-customers
    behavior: create
    files:
    - ressources/header.png
    options:
      labels:
        type: generated

