apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: acme-contracts-dashboard

resources:
  - manifests/namespace.yaml
  - manifests/deployment.yaml
  - manifests/config.yaml